<a href="https://colab.research.google.com/github/anjalireddygaddam/INFO-5731-Inclass_Exercises/blob/main/InclassExercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Write a Python program to find the duplicate elements in a given array of integers. Return -1 If there are no such elements.

def duplicateElementCheck(numbers):
    duplicateElements: list = []
    for number in range(0, len(numbers)):
        for index in range(number+1, len(numbers)):
            if(numbers[number] == numbers[index]):
                duplicateElements.append(number)
    if(len(duplicateElements) > 0):
        print("Below Duplicate elements Found")
        print(duplicateElements)
        pass
    else:
        print("No Duplicate elements Found")
        return -1


numberArray = [10, 11, 12, 22, 33, 23, 44, 2, 32, 72]
duplicateElementCheck(numberArray)

No Duplicate elements Found


-1

In [2]:
# Write a Python program to select all the Sundays of a specified year.

from datetime import date
import calendar


def findSundaysInAGivenYear(year: int):
    calendarToCheck = calendar.TextCalendar(calendar.SUNDAY)
    for month in range(1, 13):
        for day in calendarToCheck.itermonthdays(year, month):
            if day != 0:
                dayIndex = date(year, month, day)
                if(dayIndex.weekday() == 6):
                    print(year, month, day)


findSundaysInAGivenYear(2021)

2021 1 3
2021 1 10
2021 1 17
2021 1 24
2021 1 31
2021 2 7
2021 2 14
2021 2 21
2021 2 28
2021 3 7
2021 3 14
2021 3 21
2021 3 28
2021 4 4
2021 4 11
2021 4 18
2021 4 25
2021 5 2
2021 5 9
2021 5 16
2021 5 23
2021 5 30
2021 6 6
2021 6 13
2021 6 20
2021 6 27
2021 7 4
2021 7 11
2021 7 18
2021 7 25
2021 8 1
2021 8 8
2021 8 15
2021 8 22
2021 8 29
2021 9 5
2021 9 12
2021 9 19
2021 9 26
2021 10 3
2021 10 10
2021 10 17
2021 10 24
2021 10 31
2021 11 7
2021 11 14
2021 11 21
2021 11 28
2021 12 5
2021 12 12
2021 12 19
2021 12 26


In [ ]:
# Write a program to read all the txt files and save the sentences in all the files into one csv file with two columns, the first column is sentence id (txt file name+sentence line number), the second column is the sentence text content.

import pandas
import os


def createCSVFile(directory: str, csvFileName: str):
    for filename in os.listdir(directory):
        if(filename.endswith(".txt")):
            completeFilePath = os.path.join(
                directory, filename)
            df = pandas.read_csv(
                completeFilePath, sep="\t", header=None)
            indexLine = []
            for row in range(0, df.last_valid_index()+1):
                indexLine.insert(row, filename+str(row))
            df.insert(1, "", indexLine, True)
            df.to_csv(path_or_buf=directory+csvFileName, mode='a', index=False, sep=",",
                      header=None)


createCSVFile("directory/assignment", "csvFileName.csv")

# Remove all the punctuations from the sentences, save the processed sentences into a new column in the same csv file.

import csv
import os
userinput = input("Enter a word: ")
with open("output.csv",'r') as inputfile:
    filereader = csv.reader(inputfile)
    for row in filereader:
        searchterm =  "userinput" 
        if searchterm in row[2]:
            foundwords = os.findall(search_term,row[2])
            print(row[0],row[1],len(found_words))

  # Ask the user to enter a word, return all the sentences that include this word, three kinds of information should be returned: sentence id, sentence text content, the count that user input word appear in the sentence..

  import csv
import re
temporarydata = [] 
with open("output.csv",'r') as inputfile:
    filereader = csv.reader(inputfile) 
    for row in filereader:
        line = re.sub(r"[^a-zA-Z\s\']","",row[1]) 
        line = re.sub("\s\s"," ",line) 
        row(line) 
        temporarydata.append(row) 
with open("output.csv","w") as output_file:
    writer = csv.writer(output_file,delimiter=',') 
    writer.writerows(temp_data) 

In [ ]:
# Install packages nltk, numpy, scipy, pandas, and sklearn on Google Colab. Write a program to test whether they are installed successfully.

In [ ]:
! pip install nltk
! pip install numpy
! pip install scipy
! pip install pandas
! pip install scikit-learn

In [3]:
#test nltk

from nltk.tokenize import TweetTokenizer
tknz = TweetTokenizer()
s0 = "INFO 5731 and some arrows < > :: :> <: -> <--"
print(tknz.tokenize(s0))
print("**")

#test numpy

import numpy as np
nums2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(nums2d)

#test spicy

import numpy as np
from scipy import linalg
A = np.array([[1,2], [4,3]])
B = linalg.inv(A)
print(B)

#test pandas

import pandas as pd
datas = {'me' : [1,2], 'you' : [9,8]}
row_labels = [101, 102, 103, 104, 105, 106, 107]
df = pd.DataFrame(data=datas,)
print(df)



# test scikit learn

from sklearn import datasets
# Load data
iris= datasets.load_iris()
# Print shape of data to confirm data is loaded
print(iris.data.shape)

['INFO', '5731', 'and', 'some', 'arrows', '<', '>', '::', ':', '>', '<', ':', '->', '<--']
**
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.6  0.4]
 [ 0.8 -0.2]]
   me  you
0   1    9
1   2    8
(150, 4)
